name: news_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  go_router: ^9.0.3 # navigate between screens
  url_launcher: ^6.1.12 # open external urls in web browser (web view)

  dio: ^5.2.1+1 # manage http requests
  freezed_annotation: ^2.4.1 # partial requirement of freezed
  intl: ^0.18.1 # format date and time

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6 # aids freezed to generate boilerplate code
  freezed: ^2.4.1 # generate boilerplate code for data classes

flutter:
  uses-material-design: true
